import type { Question } from "../types";

/**
 * Context module — runs before Roots. Captures the practical constraints that
 * actually drive university recommendations: budget, geography, family pressure,
 * tier ambition, timeline. Every student answers all of these.
 */
export const CONTEXT_QUESTIONS: Question[] = [
  {
    id: "ctx_budget",
    section: "context",
    kind: "context",
    type: "single_choice",
    category: "Budget",
    prompt: "What's the rough annual budget your family is comfortable with for college?",
    hint: "Tuition + living, INR. Honest answer here saves you from a dream-school heartbreak later.",
    options: [
      { id: "b1", label: "Under ₹5L / year",       tag: "budget:<5L" },
      { id: "b2", label: "₹5L – ₹15L / year",      tag: "budget:5-15L" },
      { id: "b3", label: "₹15L – ₹30L / year",     tag: "budget:15-30L" },
      { id: "b4", label: "₹30L+ / year",           tag: "budget:30L+" },
      { id: "b5", label: "Honestly not sure yet",  tag: "budget:unsure" },
    ],
  },
  {
    id: "ctx_geo",
    section: "context",
    kind: "context",
    type: "multi_choice",
    category: "Where",
    prompt: "Where would you actually be willing to study?",
    hint: "Pick anything that's a real option. Not where it'd be cool — where you'd actually go.",
    options: [
      { id: "g1", label: "India",          tag: "geo:in" },
      { id: "g2", label: "UK",             tag: "geo:uk" },
      { id: "g3", label: "US / Canada",    tag: "geo:na" },
      { id: "g4", label: "Europe (non-UK)", tag: "geo:eu" },
      { id: "g5", label: "Singapore / Asia", tag: "geo:asia" },
      { id: "g6", label: "Australia / NZ", tag: "geo:anz" },
      { id: "g7", label: "Open to anywhere", tag: "geo:open" },
    ],
  },
  {
    id: "ctx_family",
    section: "context",
    kind: "context",
    type: "single_choice",
    category: "Family",
    prompt: "How much room do you have to choose your own path?",
    hint: "No judgment either way. We just need to know what we're working with.",
    options: [
      { id: "f1", label: "Total freedom — they'll back whatever I pick",     tag: "family:free" },
      { id: "f2", label: "Strong opinions, but they'll listen to a real plan", tag: "family:opinions" },
      { id: "f3", label: "Pretty specific course/career they expect",        tag: "family:specific" },
      { id: "f4", label: "Locked in — almost no flexibility",                tag: "family:locked" },
    ],
  },
  {
    id: "ctx_tier",
    section: "context",
    kind: "context",
    type: "single_choice",
    category: "Ambition",
    prompt: "When you picture the kind of college you want to land at, what's the vibe?",
    options: [
      { id: "t1", label: "Top-tier global (Ivies, Oxbridge, top US/UK)",  tag: "tier:global-top" },
      { id: "t2", label: "Strong global, just not the household names",   tag: "tier:global-mid" },
      { id: "t3", label: "Top of the Indian system (IIT/IIM/NID/NLU…)",   tag: "tier:in-top" },
      { id: "t4", label: "Solid Indian college, good fit > prestige",     tag: "tier:in-fit" },
      { id: "t5", label: "Honestly, I just want to figure it out",        tag: "tier:unsure" },
    ],
  },
  {
    id: "ctx_timeline",
    section: "context",
    kind: "context",
    type: "single_choice",
    category: "Timeline",
    prompt: "When are you applying?",
    options: [
      { id: "tl1", label: "This cycle (next 6 months)",  tag: "tl:now" },
      { id: "tl2", label: "Next cycle (~1 year out)",    tag: "tl:1y" },
      { id: "tl3", label: "2+ years out, planning early", tag: "tl:2y" },
      { id: "tl4", label: "Not decided yet",             tag: "tl:open" },
    ],
  },
  {
    id: "ctx_dream",
    section: "context",
    kind: "context",
    type: "short_text",
    category: "Dream",
    prompt: "Picture yourself five years from now on a really good day. What are you doing?",
    hint: "One or two sentences. No pressure, no right answer — just whatever first comes to mind.",
  },
  {
    id: "ctx_hobbies",
    section: "context",
    kind: "context",
    type: "multi_choice",
    category: "Free time",
    prompt: "When you have a free Sunday, what's most likely to fill it?",
    hint: "Pick all that apply — what you actually do, not what'd sound impressive.",
    options: [
      { id: "h1", label: "Reading (fiction, non-fiction, anything)", tag: "hobby:reading" },
      { id: "h2", label: "Gaming or watching content (YouTube, Netflix, anime)", tag: "hobby:screens" },
      { id: "h3", label: "Sports or working out", tag: "hobby:physical" },
      { id: "h4", label: "Music — playing or producing", tag: "hobby:music" },
      { id: "h5", label: "Building / coding / making things", tag: "hobby:building" },
      { id: "h6", label: "Art, design, photography", tag: "hobby:art" },
      { id: "h7", label: "Hanging out with friends / family", tag: "hobby:social" },
      { id: "h8", label: "Volunteering / activism / community work", tag: "hobby:cause" },
      { id: "h9", label: "Cooking / experimenting in the kitchen", tag: "hobby:cooking" },
      { id: "h10", label: "Just resting and recovering", tag: "hobby:rest" },
    ],
  },
  {
    id: "ctx_values",
    section: "context",
    kind: "context",
    type: "multi_choice",
    category: "Values",
    prompt: "When you imagine 'a life well lived', which of these matter most to you?",
    hint: "Top 3 ideally. Be honest with yourself — not the Instagram answer.",
    options: [
      { id: "v1", label: "Financial independence and security",  tag: "val:money" },
      { id: "v2", label: "Recognition for what I build / make",  tag: "val:recognition" },
      { id: "v3", label: "Deep, meaningful relationships",       tag: "val:relationships" },
      { id: "v4", label: "Adventure, travel, novelty",           tag: "val:adventure" },
      { id: "v5", label: "Mastery — being genuinely good at something", tag: "val:mastery" },
      { id: "v6", label: "Helping others / leaving things better", tag: "val:impact" },
      { id: "v7", label: "Freedom and autonomy over my time",    tag: "val:autonomy" },
      { id: "v8", label: "Creative expression",                  tag: "val:creative" },
      { id: "v9", label: "Family stability and roots",           tag: "val:family" },
      { id: "v10", label: "Status and influence",                tag: "val:status" },
    ],
  },
  {
    id: "ctx_self",
    section: "context",
    kind: "context",
    type: "short_text",
    category: "Identity",
    prompt: "If a stranger asked you 'so, what kind of person are you?' — how would you actually answer?",
    hint: "Three sentences max. No CV-speak. The version you'd say to a friend's older sibling at a wedding.",
  },
  {
    id: "ctx_energy_clock",
    section: "context",
    kind: "context",
    type: "single_choice",
    category: "Daily clock",
    prompt: "When in the day are you actually at your sharpest?",
    options: [
      { id: "ec1", label: "Early morning — I do my best work before 10 AM",       tag: "clock:morning" },
      { id: "ec2", label: "Mid-day — settled in by 11, peak around 2",            tag: "clock:midday" },
      { id: "ec3", label: "Evening — I really get going after the sun's down",    tag: "clock:evening" },
      { id: "ec4", label: "Late night — between 10 PM and 2 AM is where I live",  tag: "clock:night" },
      { id: "ec5", label: "Honestly chaotic — depends on the week",                tag: "clock:variable" },
    ],
  },
];
