"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import {
  Answer,
  AssessmentState,
  Question,
  Reaction,
  Section,
  StudentProfile,
  Archetype,
} from "./types";
import { getQuestionBank } from "./flow";
import { computeDimensionScores, pickArchetype } from "./archetype";
import { supabase } from "./supabase";

const ROOTS_ADAPTIVE_BUDGET = 3; // probes interleaved across Roots
const ROUTES_ADAPTIVE_BUDGET = 2;

interface Store extends AssessmentState {
  setProfile: (p: StudentProfile) => void;
  /** Submit (or update) an answer for a question. */
  answer: (questionId: string, partial: Partial<Answer>) => void;
  /** React to a question (insta-style). */
  react: (questionId: string, reaction: Reaction) => void;
  /** Replace the in-progress trunk with a new ordered list. */
  setTrunk: (ids: string[]) => void;
  /** Append an adaptive question generated by /api/probe. */
  pushAdaptive: (q: Question) => void;
  /** Store a rewrite for an existing question id (negative-reaction rephrase). */
  setRewrite: (questionId: string, q: Question) => void;
  /** Move to a section (used by archetype computation, transitions). */
  setSection: (s: Section) => void;
  /** Compute archetype from current Roots answers. */
  computeArchetype: () => Archetype;
  /** Reset everything (for "start over"). */
  reset: () => void;
  /** Get the question by id from any bank or adaptive set, with rewrite applied. */
  getQuestion: (id: string) => Question | undefined;
  /** All questions known so far (banks + adaptives + rewrites), for scoring/report. */
  allQuestions: () => Question[];
}

const initial: AssessmentState = {
  profile: null,
  answers: {},
  trunk: [],
  adaptiveQuestions: {},
  rewrites: {},
  section: "main_character",
};

export const useAssessment = create<Store>()(
  persist(
    (set, get) => ({
      ...initial,

      setProfile: (profile) => set({ profile }),

      answer: (questionId, partial) => {
        set((s) => ({
          answers: {
            ...s.answers,
            [questionId]: {
              ...s.answers[questionId],
              questionId,
              answeredAt: Date.now(),
              ...partial,
            },
          },
        }));

        // Save to Supabase
        const studentId = get().profile?.studentId;
        if (studentId) {
          const answer = { ...get().answers[questionId], ...partial };
          supabase.from("student_answers").upsert({
            student_id: studentId,
            question_id: questionId,
            option_ids: answer.optionIds ?? [],
            text_response: answer.text ?? null,
            reaction: answer.reaction ?? null,
          }).then(({ error }) => {
            if (error) console.error("Answer save error:", error);
          });
        }
      },

      react: (questionId, reaction) =>
        set((s) => ({
          answers: {
            ...s.answers,
            [questionId]: {
              ...s.answers[questionId],
              questionId,
              answeredAt: Date.now(),
              reaction,
            },
          },
        })),

      setTrunk: (trunk) => set({ trunk }),

      pushAdaptive: (q) =>
        set((s) => ({
          adaptiveQuestions: { ...s.adaptiveQuestions, [q.id]: q },
        })),

      setRewrite: (questionId, q) =>
        set((s) => ({ rewrites: { ...s.rewrites, [questionId]: q } })),

      setSection: (section) => set({ section }),

      computeArchetype: () => {
        const all = get().allQuestions().filter((q) => q.section === "main_character" || q.section === "skill_check");
        const scores = computeDimensionScores(all, get().answers);
        const archetype = pickArchetype(scores);
        set({ archetype });
        return archetype;
      },

      reset: () => set({ ...initial }),

      getQuestion: (id) => {
        const rewrites = get().rewrites;
        if (rewrites[id]) return rewrites[id];
        const adaptive = get().adaptiveQuestions[id];
        if (adaptive) return adaptive;
        const level = get().profile?.educationLevel;
        return getQuestionBank(level).find((q) => q.id === id);
      },

      allQuestions: () => {
        const rewrites = get().rewrites;
        const level = get().profile?.educationLevel;
        return [
          ...getQuestionBank(level).map((q) => rewrites[q.id] ?? q),
          ...Object.values(get().adaptiveQuestions).map((q) => rewrites[q.id] ?? q),
        ];
      },
    }),
    {
      name: "roots-and-routes-assessment",
      storage: createJSONStorage(() => localStorage),
      version: 1,
    },
  ),
);

export const ADAPTIVE_BUDGETS = {
  roots: ROOTS_ADAPTIVE_BUDGET,
  routes: ROUTES_ADAPTIVE_BUDGET,
};
